from __future__ import annotations

from .config import Source


DEFAULT_SOURCES: tuple[Source, ...] = (
    Source(
        name="OpenAI News",
        type="rss",
        priority="P0",
        url="https://openai.com/news/rss.xml",
        tags=["official", "ai-models"],
    ),
    Source(
        name="Anthropic News",
        type="web",
        priority="P0",
        url="https://www.anthropic.com/news",
        tags=["official", "ai-models", "claude"],
    ),
    Source(
        name="Google DeepMind Blog",
        type="rss",
        priority="P0",
        url="https://deepmind.google/blog/rss.xml",
        tags=["official", "ai-models", "research"],
    ),
    Source(
        name="Google Research Blog",
        type="rss",
        priority="P0",
        url="https://research.google/blog/rss/",
        tags=["official", "ai-models", "research"],
    ),
    Source(
        name="Meta AI Blog",
        type="web",
        priority="P0",
        url="https://ai.meta.com/blog/",
        tags=["official", "ai-models", "research"],
    ),
    Source(
        name="Microsoft AI Blog",
        type="rss",
        priority="P0",
        url="https://blogs.microsoft.com/ai/feed/",
        tags=["official", "ai-models", "enterprise-ai"],
    ),
    Source(
        name="NVIDIA AI Blog",
        type="rss",
        priority="P0",
        url="https://developer.nvidia.com/blog/category/artificial-intelligence/feed/",
        tags=["official", "ai-infra", "inference"],
    ),
    Source(
        name="AWS Machine Learning Blog",
        type="rss",
        priority="P0",
        url="https://aws.amazon.com/blogs/machine-learning/feed/",
        tags=["official", "cloud-ai", "software-delivery"],
    ),
    Source(
        name="Hugging Face Blog",
        type="rss",
        priority="P0",
        url="https://huggingface.co/blog/feed.xml",
        tags=["official", "open-source", "ai-models"],
    ),
    Source(
        name="GitHub Changelog",
        type="rss",
        priority="P0",
        url="https://github.blog/changelog/feed/",
        tags=["official", "github", "software-delivery"],
    ),
    Source(
        name="GitHub Copilot Blog",
        type="rss",
        priority="P0",
        url="https://github.blog/ai-and-ml/github-copilot/feed/",
        tags=["official", "github", "ai-coding"],
    ),
    Source(
        name="OpenAI Codex",
        type="rss",
        priority="P0",
        url="https://openai.com/news/rss.xml",
        tags=["official", "ai-coding", "codex"],
    ),
    Source(
        name="Anthropic Claude Code",
        type="web",
        priority="P0",
        url="https://www.anthropic.com/claude-code",
        tags=["official", "ai-coding", "claude-code"],
    ),
    Source(
        name="Cursor Blog",
        type="web",
        priority="P0",
        url="https://cursor.com/blog",
        tags=["official", "ai-coding", "developer-tools"],
    ),
    Source(
        name="Windsurf Blog",
        type="web",
        priority="P0",
        url="https://windsurf.com/blog",
        tags=["official", "ai-coding", "developer-tools"],
    ),
    Source(
        name="Sourcegraph Blog",
        type="web",
        priority="P0",
        url="https://sourcegraph.com/blog",
        tags=["official", "ai-coding", "developer-tools"],
    ),
    Source(
        name="JetBrains AI Blog",
        type="rss",
        priority="P0",
        url="https://blog.jetbrains.com/ai/feed/",
        tags=["official", "ai-coding", "developer-tools"],
    ),
    Source(
        name="GitLab AI Blog",
        type="web",
        priority="P0",
        url="https://about.gitlab.com/blog/categories/ai-ml/",
        tags=["official", "ai-coding", "software-delivery"],
    ),
    Source(
        name="Harness Blog",
        type="rss",
        priority="P0",
        url="https://www.harness.io/blog/rss.xml",
        tags=["official", "software-delivery", "ci-cd"],
    ),
    Source(
        name="CodeRabbit Blog",
        type="web",
        priority="P0",
        url="https://www.coderabbit.ai/blog",
        tags=["official", "ai-coding", "code-review"],
    ),
    Source(
        name="Cognition Devin Blog",
        type="web",
        priority="P0",
        url="https://www.cognition.ai/blog",
        tags=["official", "ai-coding", "agentic-coding"],
    ),
    Source(
        name="Factory Blog",
        type="web",
        priority="P0",
        url="https://www.factory.ai/blog",
        tags=["official", "ai-coding", "agentic-coding"],
    ),
    Source(
        name="GitHub AI Agent Search",
        type="github-search",
        priority="P0",
        url="https://api.github.com/search/repositories?q=agentic%20coding%20OR%20ai%20coding%20OR%20software%20agent",
        tags=["github", "ai-coding", "agentic-coding"],
    ),
    Source(
        name="Aider Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/Aider-AI/aider",
        tags=["github", "ai-coding", "open-source"],
    ),
    Source(
        name="OpenHands Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/All-Hands-AI/OpenHands",
        tags=["github", "ai-coding", "open-source"],
    ),
    Source(
        name="SWE-agent Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/SWE-agent/SWE-agent",
        tags=["github", "ai-coding", "open-source"],
    ),
    Source(
        name="Continue Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/continuedev/continue",
        tags=["github", "ai-coding", "open-source"],
    ),
    Source(
        name="Cline Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/cline/cline",
        tags=["github", "ai-coding", "open-source"],
    ),
    Source(
        name="Roo Code Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/RooCodeInc/Roo-Code",
        tags=["github", "ai-coding", "open-source"],
    ),
    Source(
        name="SWE-bench Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/SWE-bench/SWE-bench",
        tags=["github", "benchmark", "software-delivery"],
    ),
    Source(
        name="Terminal-Bench Releases",
        type="github-releases",
        priority="P0",
        url="https://github.com/laude-institute/terminal-bench",
        tags=["github", "benchmark", "software-delivery"],
    ),
    Source(
        name="arXiv AI Software Engineering",
        type="arxiv",
        priority="P0",
        url="https://export.arxiv.org/api/query?search_query=all:%28agentic%20coding%20OR%20software%20engineering%20agents%20OR%20RAG%20OR%20multimodal%20LLM%29&sortBy=submittedDate&sortOrder=descending&max_results=25",
        tags=["research", "paper", "ai-coding", "software-delivery"],
    ),
    Source(
        name="Hacker News AI Search",
        type="hn-feed",
        priority="P0",
        url="https://hnrss.org/newest?q=agentic%20coding%20OR%20AI%20agent%20OR%20LLM%20developer%20tools",
        tags=["community", "ai-coding", "software-delivery"],
    ),
)
